version: '3.8'

services:
  web:
    build: /Users/andreyyurlov/Projects/Django_v3/myproject/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./myproject/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=myproject
      - POSTGRES_PASSWORD=myproject
      - POSTGRES_DB=myproject_dev

volumes:
  postgres_data: