# Generated by Django 4.2.5 on 2023-11-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
    ]
